### ISSUE TITLE
Sidebar totally disappearing in mobile view

### ISSUE THREAD

**Issue by section117** [laravel-frontend-presets/black-dashboard#12]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Yes] I am running the latest version
- [Yes ] I checked the documentation and found no answer
- [Yes ] I checked to make sure that this issue has not already been filed
- [Yes ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

The sidebar is supposed to work in mobile view too. There should be a button to toggle the sidebar.

# Current Behavior

The sidebar totally disappear in the mobile view. And there is no button to toggle it. And also the name of the page
in the top left corner (Dashboard, Icons, Maps...) is missing from view.

# Failure Information (for bugs)

## Steps to Reproduce

Just change the width of browser window.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Asus Laptop/ Android Smartphone
* Operating System: Windows 10
* Browser and Version: Opera (Latest version)/ Google Chrome (Latest version)

## Additional Images

![102846674-9b569e80-4436-11eb-958d-4c836437935f](https://user-images.githubusercontent.com/62211634/102908562-a690e500-449d-11eb-9567-914bcf8420f6.jpeg)
Screenshot from Black Dashboard Laravel Pro. (It's working fine in this template.)

![102846734-c7721f80-4436-11eb-8c7e-319d29866237](https://user-images.githubusercontent.com/62211634/102908693-d213cf80-449d-11eb-8588-e6aa1c681862.jpeg)
Screenshot from Black Dashboard (It's working fine in this template too.)
https://github.com/creativetimofficial/black-dashboard

![102846703-b3c6b900-4436-11eb-8f61-bb42e03e6a4f](https://user-images.githubusercontent.com/62211634/102908823-ff607d80-449d-11eb-84d5-aceda3ef3d9d.jpeg)
Screenshot from this template. As I have circled from blue color, there's no name of the page in the upper eft corner. And also the sidebar doesn't work.

Thankyou for your attention!

**Comment by teamupdivision** [comment]
Hello @section117 
Thank you for using our products.
Also, thanks for the feedback on the free version of Black Dashboard Laravel.
We'll follow up with a fix in the next weeks after the winter holidays.

All the best!

**Comment by teamupdivision** [comment]
Hello @section117

We took care of the issue you reported.
We pushed the update to the repo and the product archive, and also pulled the changes to the demo site.
Feel free to reopen this issue if you find anymore problems.

Have a good day!
