### ISSUE TITLE
CSS and JS not working on fresh install

### ISSUE THREAD

**Issue by jj2405** [laravel-frontend-presets/black-dashboard#2]
Hello,

I have installed the free version on a fresh install of laravel and have found that the styles are not working. The pages work and the style sheets and JS are included but they respond with 404 errors. How can I fix this? Where should they be stored? I installed using composer so everything should have been installed correctly.

**Comment by teamupdivision** [comment]
Hello @jj2405, thank you for using our products!

Can you please check in the browser inspector if the paths to the css and js files are correct? Please copy paste them here.
It would be useful if you send us the exact steps you did for the install.

Thank you

**Comment by jj2405** [comment]
Hello,

Thanks for your reply! Here are the errors from the browser console. I installed a fresh Laravel instance and then followed the steps found on the documentation for a composer install.

Thanks for your help!

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (nucleo-icons.css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (theme.css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (black-dashboard.css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (jquery.min.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (popper.min.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (perfect-scrollbar.jquery.min.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bootstrap.min.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (black-dashboard.min.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bootstrap-notify.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (theme.js, line 0)
[Error] ReferenceError: Can't find variable: $
	Global Code (openfoodnetwork.co.za:169)

**Comment by teamupdivision** [comment]
Thank you for the reply, can you also paste the relative paths of the Javascript files?

**Comment by jj2405** [comment]
Apologies for the slow response! Here is a screenshot of the error log. Please note the domain is not active and is being served from a private server. Thanks!

<img width="1439" alt="Screenshot 2020-01-21 at 18 00 41" src="https://user-images.githubusercontent.com/59567886/72830154-096b7200-3c78-11ea-80c7-e102e8765a01.png">

**Comment by jj2405** [comment]
I believe the problem was caused by my server setup. Not sure what it was but I have moved to a hosted server now and the admin panel works fine for me now. Thanks for your help!

**Comment by teamupdivision** [comment]
Hello, I'm really glad the problem got solved.

All the best!
