### ISSUE TITLE
php artisan preset black not working

### ISSUE THREAD

**Issue by eadortsu** [laravel-frontend-presets/black-dashboard#6]
running 'php artisan preset black' in laravel 7.x not working.
run 'php artisan ui black' insted

**Comment by teamupdivision** [comment]
Hello @eadortsu, thank you for using our products!

The readme is up to date, we'll update also the docs files.

Thank you very much

**Comment by cdbessig** [comment]
The website is still not up2date.  https://www.creative-tim.com/product/black-dashboard-laravel#

**Comment by teamupdivision** [comment]
Hi @cdbessig,

Thank you for reporting this issue and for using Creative Tim products.
 
Could you please send a few more details to us? We were not able to reproduce any error. Also, if you can send to us a screenshot or video recording with the steps, it will help a lot in investigating this further.
 
All the best,
UPDIVISION Team

**Comment by cdbessig** [comment]
It's that the doumentaiton doesn't mention anything about 'php artisan preset black' in laravel 7.x not working.
run 'php artisan ui black' instead

See screenshot: https://share.getcloudapp.com/DOuqQbQv

I wasted some time, but luckily got brought to this issue.

**Comment by teamupdivision** [comment]
Hi @cdbessig,

Thank you very much for the clarification and for letting us know. We'll update this soon. 

Also, if you have any questions or issues, please feel free to contact us anytime.

Best,
UPDIVISION Team
